### PR TITLE
Fix increments

### LINKED ISSUE #1: Surprising result from increment-major
I was a bit surprised to see that increment major works this way:

```
user> (s/transform s/increment-major "0.1.2")
1.1.2
```

I would have expected to get `1.0.0` instead as next major version.
It's not hard to change it make my own function to fill in the desired zeros, but I wonder why it was done this way?

### PR DESCRIPTION
**Pull request by AndreaCrotti**
Fixes #1 by resetting the other components when a new version is generated

### CODE REVIEW

**Comment by AndreaCrotti** [comment]
Any news about this @owainlewis ?
Otherwise in the meanwhile I'll probably have to use my fork and push it to Clojars or similar.
Thanks!

**Comment by AndreaCrotti** [comment]
Hi @owainlewis, hope you don't mind but since I needed these fixes I created a fork
https://github.com/andreacrotti/semver

and I deployed that to clojars, so I can use it in a few projects.

**Comment by esuomi** [comment]
Hi @AndreaCrotti 

I hit this same exact issue today. Do you want take over the development of this library in your fork or would you rather want @owainlewis to continue development or someone else to continue the work?

**Comment by AndreaCrotti** [comment]
Hi @esuomi , I needed the fix so since I've just forked here and pushed on Clojars last week
https://github.com/AndreaCrotti/semver
https://clojars.org/andreacrotti/semver

Feel free to use that if you want, and I'm also happy to take over development otherwise but that depends on @owainlewis

**Comment by owainlewis** [comment]
Since it seems to be a problem other's are facing I'll merge this. Thanks 👍

**Pull request merged**
